### ISSUE TITLE
The `--no_slurm` worked on my EC2!  But only uses 1 cpu and very slow.

### ISSUE THREAD

**Issue by Yang-Wang-2020** [Jnelen/DiffDockHPC#2]
`$ python inferenceVS.py -p data/1a0q/1a0q_protein_processed.pdb -l data/1a0q/ -out TEST -j 1 -gpu --no_slurm`

No protein embeddings present, generating now..
Generating ESM language model embeddings **(this step used GPU!)**
Processing 1 of 1 batches (2 sequences)
converted protein to lm embeddings
Launching jobs now..
Precomputing and saving to cache SO(3) distribution table
**Then it uses 1 CPU and is very slow.**

Precomputing and saving to cache torus distribution table
**Still uses 1 CPU and is very slow.**

BTW: Looking forward to the DiffDock-L version!

**Comment by Yang-Wang-2020** [comment]
I figured it out. I should use `--cores` to use more cores. Thank you!

**Comment by Jnelen** [comment]
> I figured it out. I should use `--cores` to use more cores. Thank you!

Hi, glad to hear it works better now! Just to be sure however: is the GPU also being used during the inference now?
Also, if you use the --no-slurm flag, everything will be ran on a single GPU. If you have slurm setup and installed on your system, it usually is better to use this (if you want to perform calculations for many different ligands). If you have slurm on your system I can try to help to make that work better. However if you don't have it installed it's probably better like this

Finally, it is normal for the precomputing to be very slow, but only needs to happen once. So from here it should be fine!

**Comment by Jnelen** [comment]
@Yang-Wang-2020 I just updated DiffDockHPC to use DiffDock v1.1! Feel free to try it out, I would recommend a clean install however, since quite a few things changed!

**Comment by Yang-Wang-2020** [comment]
Worked on my instance! Thanks a ton.

**Comment by Jnelen** [comment]
> Worked on my instance! Thanks a ton.

Awesome, glad to hear that! If you run into anything or have any questions, don't hesitate to reach out!
