### ISSUE TITLE
Question about the output naming. How should I understand the ranking and confidence?

### ISSUE THREAD

**Issue by Yang-Wang-2020** [Jnelen/DiffDockHPC#4]
I tried and generated 10 outputs with rankings from 1 to 10. However, the confidence scores (according to the filename) range from 0.24 (rank 1) to 1.19 (rank 10). Does this mean the rank 1 output has the lowest confidence? 
Thank you!
Yang

**Comment by Jnelen** [comment]
Hi there,

Normally the higher the confidence the better. To quote the DiffDock authors:
> How to interpret the DiffDock output confidence score?
> It can be hard to interpret and compare confidence score of different complexes or different protein conformations, however, here a rough guideline that we typically use (c is the confidence score of the top pose):
> c > 0 high confidence
> -1.5 < c < 0 moderate confidence
> c < -1.5 low confidence
> This is assuming the complex is similar to what DiffDock saw in the training set i.e. a not too large drug-like molecule bound to medium size protein (1 or 2 chains) in a conformation that is similar to the bound one (e.g. if it comes from an homologue crystal structure). If you are dealing with a large ligand, a large protein complex and/or an app/unbound protein conformation you should shift these intervals down.

However, as you indicated above, a confidence score can also be negative. Could you open the rank1 and rank10 sdf files using a text editor, and look at the "DiffDock_Confidence" property? Is the rank10 confidence score a positive number here as well?

**Comment by Yang-Wang-2020** [comment]
You are 100% right. The score is negative in the file. Everything makes sense now. Thank you!

**Comment by Jnelen** [comment]
> You are 100% right. The score is negative in the file. Everything makes sense now. Thank you!

Glad to help and great to hear that it works correctly! In the filename, the score should also be indicated as negative, but it's hard to miss because it just looks like a dash which is part of the filename.
