### ISSUE TITLE
Could you add support for --protein_ligand_csv and support for SMILES for ligand e.g. --ligand "COc(cc1)ccc1C#N"?

### ISSUE THREAD

**Issue by Yang-Wang-2020** [Jnelen/DiffDockHPC#5]
Hi Jochem, 

I found it could be really useful to use the "--protein_ligand_csv" option for batch jobs. 

Thank you,
Yang

**Comment by Yang-Wang-2020** [comment]
Never mind, I figured out how to use the protein_ligand_csv. 

Cheers,
Yang

**Comment by Jnelen** [comment]
> Never mind, I figured out how to use the protein_ligand_csv.
> 
> Cheers, Yang

Hi there, 

It's possible by calling inference.py directly. However, I don't think this is not convenient from a user POV. I'm working on implementing support for the protein_ligand_csv option directly from `inferenceVS.py`. It will basically split the csv file into separate smaller csv files, and then launch them as jobs like the other option. I need to change and check some other minor things as well to ensure compatibility. After I test it I will push the update! I hope to do this either later today, or otherwise tomorrow.

**Comment by Yang-Wang-2020** [comment]
Thank you. As you mentioned, I was using the inference.py directly.
Best,
Yang

**Comment by Jnelen** [comment]
> Thank you. As you mentioned, I was using the inference.py directly. Best, Yang

Hi, 

I just pushed some changes. Could you try it out? The protein_ligand_csv can contain different proteins, however, it will all be stored in the `molecules/` directory. But at least the --protein_ligand_csv option can now be used from inferenceVS.py, which means it can be run using slurm, and also across multiple jobs! Can I ask you what exactly is your usecase by the way? Perhaps there is an option to save the ligands per protein target, but this might complicate the code quite a bit, and perhaps in that case it's easier to use regular DiffDock?

Kind regards,
Jochem

**Comment by Jnelen** [comment]
Actually I just made some additional changes, and now it does group the output molecules per protein file (if there is more than 1). The implementation is not the cleanest, but it's functional, and I think this makes a lot more sense! Please try it out and let me know if it works for you!

**Comment by Yang-Wang-2020** [comment]
Wow, that was fast. Thank you for adding this feature. I will try it out. 
My use case is multiple pdbs vs multiple small molecules. As long as the program can take the `protein_ligand_csv`, I can name each combination in the csv. I love the HPC version because it is easy to install and easy to use. 
I also realize that the HPC inference.py takes the ';' separated csv instead of a regular csv. 

Thanks again,
Yang

**Comment by Jnelen** [comment]
> Wow, that was fast. Thank you for adding this feature. I will try it out. My use case is multiple pdbs vs multiple small molecules. As long as the program can take the `protein_ligand_csv`, I can name each combination in the csv. I love the HPC version because it is easy to install and easy to use. I also realize that the HPC inference.py takes the ';' separated csv instead of a regular csv.
> 
> Thanks again, Yang

Thanks for your kind words!
I'm very glad it is useful to you! I actually made some changes, and now csvs with ',' also should work fine. So please update to the latest version if you haven't already! Additionally, if you use --protein_ligand_csv with `inferenceVS.py`, it will now also group the ligands per protein, which I think can be very useful for your usecase. The protein files are also copied to the molecules directory, but maybe that's not useful for you? Perhaps I should make that optionial?

Thanks again for the feedback!
Jochem

**Comment by Yang-Wang-2020** [comment]
It has been very useful to me. Thank you for the work! I have pulled the latest update and will test it out soon. 

Best,
Yang

**Comment by Jnelen** [comment]
> It has been very useful to me. Thank you for the work! I have pulled the latest update and will test it out soon.
> 
> Best, Yang

Awesome, I hope it works well for you!
Any feedback is appreciated!

Kind regards,
Jochem
